name = "wordlew"
main = "dist/bundle.js"
compatibility_date = "2025-01-29"

[observability]
  enabled = true

[[kv_namespaces]]
  binding = "WORDLE_STATS" # The binding name you used in your code
  id = "ddfcacff6ac54099bc2f7cf1e8bf5250" # Your KV namespace ID