name = "wordlew"
main = "./src/index.js"
compatibility_date = "2023-05-18"

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./src/index.js"
rules = [
  { type = "ESModule", globs = ["**/*.js"] }
]

[build.upload.external]
modules = ["@turso/client"]

[observability.logs]
enabled = true